#!/usr/bin/env bash

set +x
set -o errexit
set -o nounset

CPPCHECK=$(which cppcheck)
${CPPCHECK} --version
CPPCHECK_OPTIONS="--enable=all --inconclusive --error-exitcode=1 --force"
if [[ -d "src/include" ]]; then
    CPPCHECK_INCLUDES="${CPPCHECK_INCLUDES-} -I src/include/"
fi
if [[ -d "include" ]]; then
    CPPCHECK_INCLUDES="${CPPCHECK_INCLUDES-} -I include/"
fi
if [[ -f "cppcheck_include.txt" ]]; then
   CPPCHECK_INCLUDES="${CPPCHECK_INCLUDES-} --include=cppcheck_include.txt"
fi

[[ -f "cppcheck_suppress.txt" ]] && CPPCHECK_SUPPRESS="--suppressions-list=cppcheck_suppress.txt"
[[ -z "${CPPCHECK_SOURCES-}" ]] && CPPCHECK_SOURCES="$(find src -type d)"

CPPCHECK_CMD="${CPPCHECK} ${CPPCHECK_OPTIONS} ${CPPCHECK_INCLUDES} ${CPPCHECK_SUPPRESS-} ${CPPCHECK_SOURCES}"
${CPPCHECK_CMD}
exit $?
