#!/usr/bin/env bash

set -x
set -o errexit
set -o nounset

INSTALL_PREFIX=${INSTALL_PREFIX-/usr/local}

CPPCHECK_VERSION="${CPPCHECK_VERSION-2.16.0}"
CPPCHECK_DIR=cppcheck-${CPPCHECK_VERSION}
CPPCHECK_ZIP=cppcheck-${CPPCHECK_VERSION}.zip

# cppcheck, make dir ${HOME}/projects/3thd
set +e
if [[ ! -f "${CPPCHECK_ZIP}" || ! -f "${CPPCHECK_DIR}/cppcheck" ]]; then
    wget --quiet -O "${CPPCHECK_ZIP}" https://github.com/danmar/cppcheck/archive/${CPPCHECK_VERSION}.zip
    if [[ $? -ne 0 ]]; then
        echo -e "failed download ${CPPCHECK_VERSION}.zip"
        exit 1
    fi
    if [[ -d "${CPPCHECK_DIR}" ]]; then
        rm -fr "${CPPCHECK_DIR}"
    fi
    unzip -qq "${CPPCHECK_ZIP}"
    cd "${CPPCHECK_DIR}"
    mkdir build
    cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}
    cmake --build build
    cmake --install build
    cd ..
    rm -fr ${CPPCHECK_DIR}
    rm -f ${CPPCHECK_ZIP}
fi
set -e
exit 0
