name: CMake on a single platform
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # Customize the conan profile type here (default for build type Release, debug for Debug)
  CONAN_PROFILE: default

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule init && git submodule update && git fetch --tags

    - name: Install checkers
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind clang-format-19 wget unzip lcov python3 python3-pip

    - name: Install buildfab and build tools
      run: |
        wget -O - "https://github.com/AlexBurnes/buildfab/releases/latest/download/buildfab-linux-amd64-install.sh" | sudo sh
        buildfab pre-install -vvv

    - name: Build cppcheck
      working-directory: ${{github.workspace}}
      run: sudo buildfab cppcheck-install

    - name: Source pre-checks cppcheck
      working-directory: ${{github.workspace}}
      run: buildfab cpp-check

    - name: Source pre-checks code style
      working-directory: ${{github.workspace}}
      run: buildfab style-check

    - name: Configure conan
      run: |
        conan profile detect --force
        cp ~/.conan2/profiles/default ~/.conan2/profiles/debug && sed -i -e 's/Release/Debug/g' ~/.conan2/profiles/debug

    - name: Build third libraries
      working-directory: ${{github.workspace}}
      run: buildfab conan-install

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: buildfab cmake-config

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        buildfab cmake-build
        buildfab cmake-install

    - name: Test
      working-directory: ${{github.workspace}}/.build
      run: buildfab run-test

    - name: Test benchmark
      working-directory: ${{github.workspace}}
      run: buildfab benchmark

    - name: Source post-checks memory leaks
      working-directory: ${{github.workspace}}
      run: buildfab mem-check

